### PR TITLE
Adding support for Moonbeam and Moonriver.

### PR DESCRIPTION
**Pull request by x676f64**

### CODE REVIEW

**Comment by samczsun** [comment]
unfortunately it's not as simple as adding it into the chain config file - i need an actual archive node with tracer support otherwise none of the important info will load

**Comment by x676f64** [comment]
Ah gotcha, let me see what I can do.

**Comment by x676f64** [comment]
> unfortunately it's not as simple as adding it into the chain config file - i need an actual archive node with tracer support otherwise none of the important info will load

Ah gotcha, let me see what I can do.

**Comment by ymonye** [comment]
> unfortunately it's not as simple as adding it into the chain config file - i need an actual archive node with tracer support otherwise none of the important info will load

Hey Samczsun, I read in Discord you need an RPC endpoint for an archive node with tracing. Do you still need this? If so, for how long?

**Comment by x676f64** [comment]
> > unfortunately it's not as simple as adding it into the chain config file - i need an actual archive node with tracer support otherwise none of the important info will load
> 
> Hey Samczsun, I read in Discord you need an RPC endpoint for an archive node with tracing. Do you still need this? If so, for how long?

I assume it would be on-going. Moonbeam could also choose to self-deploy the front-end if they wanted to maintain everything.

**Comment by samczsun** [comment]
Yeah, it would be ongoing for however long this project stays running, which will hopefully be a few months at least!

**Comment by samczsun** [comment]
going to close this for now, we can revisit in the future if need be

**Pull request closed without merging**
