### PR TITLE
Dark mode, Visual Improvements, Cleanup

### PR DESCRIPTION
**Pull request by Haruxe**
Does a little bit of cleanup and visual stuffs and things.
- Adds Dark mode, adds `styled-icons` for more performant svgs rather than pngs
- Small visual fixes for input buttons
- Fixes bug that occurred that caused no chain to be selected upon entering the site
- No longer handles blank user input
- A little bit of cleanup in source code, avoiding repetitious components.
- Cleaned up duplicated code in trace display to a constant tsx module `Navbar.tsx` that carries over.

### CODE REVIEW

**Comment by Haruxe** [comment]
image
mfw front end development

**Comment by samczsun** [comment]
uhhhh, wat

**Comment by samczsun** [comment]
lmao i think i bricked the pr because i cant reopen it without there being commits, and i cant push to your pr anymore because it's closed

**Comment by Haruxe** [comment]
> lmao i think i bricked the pr because i cant reopen it without there being commits, and i cant push to your pr anymore because it's closed. just gonna manually merge your commits into master. sorry D:

Lmao its alright as long as the code gets in haha

**Pull request closed without merging**
